(()=>{'use strict';
const KEY='geotec-asignacion-camioneta-v2',MONTHS=['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'];
const $=id=>document.getElementById(id),els={fecha:$('fecha'),modelo:$('modelo'),patente:$('patente'),interno:$('interno'),people:$('people-list'),alert:$('alert'),status:$('status'),download:$('download-btn')};
const initial=()=>({fecha:new Date().toLocaleDateString('en-CA'),modelo:'HILUX 2.4 DEX',patente:'',interno:'',people:[{nombre:'',cargo:'Supervisor',rut:''}]});
let state=initial();
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved&&typeof saved==='object'){state={...initial(),...saved};if(!Array.isArray(state.people)||!state.people.length)state.people=initial().people}}catch(e){}
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}};
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const formatDate=iso=>{const [y,m,d]=(iso||'').split('-').map(Number);return y&&m&&d?`${d} de ${MONTHS[m-1]} de ${y}`:''};
const cleanRut=v=>v.toUpperCase().replace(/[^0-9K]/g,'').slice(0,9);
const formatRut=v=>{const r=cleanRut(v);if(r.length<2)return r;const body=r.slice(0,-1).replace(/\B(?=(\d{3})+(?!\d))/g,'.');return `${body}-${r.slice(-1)}`};
const validRut=v=>{const r=cleanRut(v);if(r.length<8)return false;let sum=0,m=2;for(let i=r.length-2;i>=0;i--){sum+=Number(r[i])*m;m=m===7?2:m+1}const x=11-(sum%11),dv=x===11?'0':x===10?'K':String(x);return dv===r.at(-1)};
const formatPlate=v=>{const x=v.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);return x.length>4?`${x.slice(0,4)}-${x.slice(4)}`:x};
function renderPeople(){els.people.innerHTML='';state.people.forEach((p,i)=>{const row=document.createElement('div');row.className='person-row';row.innerHTML=`<div class="person-row__number">PERSONA ${i+1}</div>${state.people.length>1?`<button type="button" class="remove-button" aria-label="Eliminar persona ${i+1}">×</button>`:''}<div class="person-fields"><div class="field name-field"><label>Nombre completo <b>*</b></label><input data-key="nombre" type="text" value="${esc(p.nombre)}" placeholder="Nombre y apellidos" autocomplete="off"></div><div class="field"><label>Cargo <b>*</b></label><input data-key="cargo" type="text" value="${esc(p.cargo)}" placeholder="Supervisor" autocomplete="off"></div><div class="field"><label>RUT <b>*</b></label><input data-key="rut" type="text" value="${esc(p.rut)}" placeholder="18.575.045-0" inputmode="text" autocomplete="off"></div></div>`;
row.querySelectorAll('input').forEach(input=>input.addEventListener('input',()=>{let value=input.value;if(input.dataset.key==='rut'){value=formatRut(value);input.value=value}state.people[i][input.dataset.key]=value;input.classList.remove('invalid');save();renderPreview()}));
const remove=row.querySelector('.remove-button');if(remove)remove.addEventListener('click',()=>{state.people.splice(i,1);save();renderPeople();renderPreview()});els.people.appendChild(row)})}
function renderPreview(){$('prev-fecha').textContent=formatDate(state.fecha);$('prev-modelo').textContent=state.modelo||'—';$('prev-patente').textContent=state.patente||'—';$('prev-interno').textContent=state.interno||'—';$('doc-code').textContent=`REG-CAM${state.interno?` · ${state.interno}`:''}`;const body=$('prev-table-body');body.innerHTML=state.people.map(p=>`<tr><td>${esc(p.nombre)||'&nbsp;'}</td><td>${esc(p.cargo)||'&nbsp;'}</td><td>${esc(p.rut)||'&nbsp;'}</td><td>&nbsp;</td></tr>`).join('');const required=[state.fecha,state.modelo,state.patente,state.interno,...state.people.flatMap(p=>[p.nombre,p.cargo,p.rut])];const done=required.filter(Boolean).length;$('completion').textContent=`${Math.round(done/required.length*100)}% completo`}
function syncForm(){els.fecha.value=state.fecha;els.modelo.value=state.modelo;els.patente.value=state.patente;els.interno.value=state.interno;renderPeople();renderPreview()}
function validate(){document.querySelectorAll('.invalid').forEach(x=>x.classList.remove('invalid'));const errors=[];[['fecha','Fecha'],['modelo','Modelo'],['patente','Patente'],['interno','N° interno']].forEach(([id,label])=>{if(!state[id].trim()){errors.push(label);els[id].classList.add('invalid')}});state.people.forEach((p,i)=>{const inputs=els.people.children[i].querySelectorAll('input');if(!p.nombre.trim()){errors.push(`Nombre de persona ${i+1}`);inputs[0].classList.add('invalid')}if(!p.cargo.trim()){errors.push(`Cargo de persona ${i+1}`);inputs[1].classList.add('invalid')}if(!p.rut.trim()||!validRut(p.rut)){errors.push(`RUT válido de persona ${i+1}`);inputs[2].classList.add('invalid')}});els.alert.hidden=!errors.length;els.alert.textContent=errors.length?`Revisa: ${errors.join(', ')}.`:'';if(errors.length)els.alert.scrollIntoView({behavior:'smooth',block:'center'});return !errors.length}
['fecha','modelo','interno'].forEach(id=>els[id].addEventListener('input',()=>{state[id]=els[id].value;els[id].classList.remove('invalid');save();renderPreview()}));
els.patente.addEventListener('input',()=>{state.patente=formatPlate(els.patente.value);els.patente.value=state.patente;els.patente.classList.remove('invalid');save();renderPreview()});
$('add-row-btn').addEventListener('click',()=>{state.people.push({nombre:'',cargo:'Supervisor',rut:''});save();renderPeople();renderPreview();els.people.lastElementChild.scrollIntoView({behavior:'smooth',block:'center'})});
$('print-btn').addEventListener('click',()=>{if(validate())window.print()});
$('reset-btn').addEventListener('click',()=>{if(!confirm('¿Limpiar todos los datos del formulario?'))return;state=initial();localStorage.removeItem(KEY);els.alert.hidden=true;els.status.textContent='Formulario restablecido.';syncForm()});
async function makePdf(){if(!window.html2canvas||!window.jspdf)throw new Error('No fue posible cargar las librerías del PDF. Revisa tu conexión.');const canvas=await html2canvas($('page'),{scale:2.2,backgroundColor:'#fff',useCORS:true,logging:false});const pdf=new window.jspdf.jsPDF({orientation:'portrait',unit:'pt',format:'letter',compress:true});pdf.addImage(canvas.toDataURL('image/jpeg',.96),'JPEG',0,0,612,792,undefined,'FAST');return pdf}
els.download.addEventListener('click',async()=>{if(!validate())return;els.download.disabled=true;els.download.innerHTML='Generando PDF…';els.status.textContent='Preparando el documento…';try{const pdf=await makePdf();const p=state.patente.replace(/[^A-Z0-9]/g,'')||'SIN_PATENTE',n=state.interno.replace(/\s/g,'')||'SIN_INTERNO';pdf.save(`ASIGNACION_CAMIONETA_${p}_${n}.pdf`);els.status.textContent='PDF generado correctamente.'}catch(e){els.alert.hidden=false;els.alert.textContent=e.message||'No se pudo generar el PDF.';els.status.textContent=''}finally{els.download.disabled=false;els.download.innerHTML='<span aria-hidden="true">↓</span> Generar PDF'}});
function scalePreview(){if(innerWidth>640){$('page').style.transform='';$('page').parentElement.style.height='';return}const available=innerWidth-24,scale=available/816;$('page').style.transform=`scale(${scale})`;$('page').parentElement.style.height=`${1056*scale+95}px`}
addEventListener('resize',scalePreview);syncForm();scalePreview();
})();
